server:
  port: 8084
spring:
  application:
    name: innovation
  datasource:
    url: jdbc:postgresql://localhost:5432/tax-dash-auth
    username: postgres
    password: stan
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:  
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: 175dollarsnow@gmail.com
    password: uiiv ryun kpzi wjpc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

  queue.name: taxdash.verification.queue
  exchange.name: taxdash.verification.exchange
  routing.key: taxdash.verification.key

amqp:
  deserialization:
    trust:
      all: true

email:
  owner: 175dollarsnow@gmail.com

jwt:
  secret: 0e7d5a5f9b1c7a8b3e2d6f0c4a9b8e1f5d7c3b9e8f1a0d2c6b4e8f9c1a0b3d5e
  expiration: 86400000 # 1 day in milliseconds
  